### ISSUE TITLE
Fix simple typo: nirgn -> nirgun

### ISSUE THREAD

**Issue by timgates42** [jnv/lists#162] opened 2020-09-25 19:59 UTC
# Issue Type

[x] Bug (Typo)

# Steps to Replicate

1. Examine README.md.
2. Search for `nirgn`.

# Expected Behaviour

1. Should read `nirgun`.

**Comment by jnv** [comment] 2020-09-25 20:19
Can't reproduce. The only instance of this string is in the entry for https://github.com/nirgn975/awesome-drupal which is correct.

Closing as invalid.

**Closed by jnv** 2020-09-25 20:19 UTC

**Comment by jnv** [comment] 2020-09-25 20:25
Wow, is this an automated process which attempts to find spelling mistakes in readmes? I appreciate the effort but it would be nice if there was a note that this was created automatically instead of it looking like an issue from human. This reeks of spamming and will be eventually blocked by GitHub.
